language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ghost' ]; then cd .. && eval "mv $currentfolder generator-ghost" && cd generator-ghost; fi

